### ISSUE TITLE
Authentication Failed when starting controller.

### ISSUE THREAD

**Issue by mekklovesfemboys** [lythx/trakman#217]
![image](https://github.com/lythx/trakman/assets/105412507/76b7f3d9-7a4c-4ef0-9a5a-6e8a8d32fdf4)

**Comment by wsrvn** [comment]
i think the error is that the password is incorrect.

**Comment by VTXSRB** [comment]
hi can you please provide more context on the error so we can help you?

**Comment by mekklovesfemboys** [comment]
idk what i did but i fixed it and created another error that is too complicated for my smooth brain
![image](https://github.com/lythx/trakman/assets/105412507/ba2cb16e-5274-4100-a995-336dcc972780)

**Comment by wsrvn** [comment]
thats #210. relaunch a few times and it will work (hopefully)

**Comment by mekklovesfemboys** [comment]
ok thanks its working now, only problem is that the game is not letting me connect to the server, is port forwarding the only way to connect or is there another way (i dont know the login to my router)

**Comment by VTXSRB** [comment]
port forwarding is the only way to host the server **locally**. if you don't want to self-host, you can use a cloud service
also for your router, search up the name/model of it on google + "default login" or something like that..
you might know this already but i'm still going to mention it, in order to actually access your router, go into your terminal and type "ip route" (on linux), and look for the "default"
 or "ipconfig" (on windows) and look for the "gateway". after this, just put it in your browser.

**Comment by wsrvn** [comment]
> ok thanks its working now, only problem is that the game is not letting me connect to the server, is port forwarding the only way to connect or is there another way (i dont know the login to my router)

you can join via lan if portforwarding really isnt an option for you (in case you're behind nat or something)

**Comment by VTXSRB** [comment]
im assuming you fixed it if not too bad
